version: '3.8'

services:
    root_db:
        image: postgres:latest
        environment:
          - POSTGRES_DB=root_db
          - POSTGRES_USER=root_user
          - POSTGRES_PASSWORD=root_password
        volumes:
          - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
        command: postgres -c listen_addresses='*' -c hba_file=/etc/postgresql/pg_hba.conf
        ports:
          - "5432:5432"
    
    shard_one_db:
        image: postgres:latest
        environment:
          - POSTGRES_DB=shard_one_db
          - POSTGRES_USER=shard_one_user
          - POSTGRES_PASSWORD=shard_one_password
        volumes:
          - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
        command: postgres -c listen_addresses='*' -c hba_file=/etc/postgresql/pg_hba.conf -p 6432
        ports:
          - "6432:6432"

    shard_two_db:
        image: postgres:latest
        environment:
          - POSTGRES_DB=shard_two_db
          - POSTGRES_USER=shard_two_user
          - POSTGRES_PASSWORD=shard_two_password
        volumes:
          - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
        command: postgres -c listen_addresses='*' -c hba_file=/etc/postgresql/pg_hba.conf -p 7432
        ports:
          - "7432:7432"